plugins:
  - jekyll-relative-links
  - jekyll-theme-cayman
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md

titles_from_headings:
  enabled: false

theme: jekyll-theme-cayman
title: Laadulliset
description: Laadullisten aineistojen työmenetelmät historiatieteessä, Antti Härkösen luennot (tekstinlouhinta, verkostoanalyysi, teemakartat)
