plugins:
  - jekyll-relative-links
  - jekyll-theme-cayman
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
theme: jekyll-theme-cayman
title: Laadullisten aineistojen työmenetelmät historiatieteessä
description: Antti Härkösen luennot (tekstinlouhinta, verkostoanalyysi, teemakartat)
